### PR TITLE
Prepare to list in Composer/Packagist

### PR DESCRIPTION
**Pull request by mbirth**
I created a composer.json and a README.md. I already [listed the package in Packagist](https://packagist.org/packages/seblucas/tbszip) from my repo, but I think it would be better if you could list the package yourself from your account. You'd only need to add a WebHook to the GitHub repo for automatic updating.

### CODE REVIEW

**Comment by seblucas** [comment]
Thanks, I never used Packagist before but I'll do what you asked tonight.

I guess https://github.com/seblucas/php-epub-meta should be next ?

**Comment by seblucas** [comment]
I created an account on Packagist but as you already registered it with your account I got this message : 

```
The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. The packages already in that vendor namespace can be found at seblucas
```

Let me know what I need to do next, thank in advance ;)

**Comment by mbirth** [comment]
I added you(seblucas?) as a maintainer for the packages. Please try again. :)

I already changed the GitHub URLs for your packages.

Here's how to setup the GitHub hook: https://packagist.org/about#how-to-update-packages

**Comment by mbirth** [comment]
Could you add a new tag 2.16.0 to the latest commit, please?

**Comment by seblucas** [comment]
Webhook done and I added a 2.16.1 tag (I added a fix after the official 2.16)

**Comment by mbirth** [comment]
Awesome! :+1:

**Pull request merged**
